# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'launchwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Launch(object):
    def setupUi(self, Launch):
        Launch.setObjectName("Launch")
        Launch.resize(593, 535)
        self.gridLayout = QtWidgets.QGridLayout(Launch)
        self.gridLayout.setObjectName("gridLayout")
        self.reader = QtWidgets.QLabel(Launch)
        self.reader.setObjectName("reader")
        self.gridLayout.addWidget(self.reader, 0, 0, 1, 1)
        self.readtext = QtWidgets.QTextBrowser(Launch)
        self.readtext.setObjectName("readtext")
        self.gridLayout.addWidget(self.readtext, 1, 0, 1, 1)
        self.recivetext = QtWidgets.QTextBrowser(Launch)
        self.recivetext.setObjectName("recivetext")
        self.gridLayout.addWidget(self.recivetext, 1, 1, 1, 1)
        self.reciver = QtWidgets.QLabel(Launch)
        self.reciver.setObjectName("reciver")
        self.gridLayout.addWidget(self.reciver, 0, 1, 1, 1)

        self.retranslateUi(Launch)
        QtCore.QMetaObject.connectSlotsByName(Launch)

    def retranslateUi(self, Launch):
        _translate = QtCore.QCoreApplication.translate
        Launch.setWindowTitle(_translate("Launch", "狐神！启动！"))
        self.reader.setText(_translate("Launch", "读取界面"))
        self.reciver.setText(_translate("Launch", "链接界面"))
