# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'launchwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Launch(object):
    def setupUi(self, Launch):
        Launch.setObjectName("Launch")
        Launch.resize(593, 535)
        self.gridLayout = QtWidgets.QGridLayout(Launch)
        self.gridLayout.setObjectName("gridLayout")
        self.recivetext = QtWidgets.QTextBrowser(Launch)
        self.recivetext.setObjectName("recivetext")
        self.gridLayout.addWidget(self.recivetext, 1, 1, 1, 1)
        self.reciver = QtWidgets.QLabel(Launch)
        self.reciver.setObjectName("reciver")
        self.gridLayout.addWidget(self.reciver, 0, 1, 1, 1)
        self.readtext = QtWidgets.QTextBrowser(Launch)
        self.readtext.setObjectName("readtext")
        self.gridLayout.addWidget(self.readtext, 1, 0, 1, 1)
        self.reader = QtWidgets.QLabel(Launch)
        self.reader.setObjectName("reader")
        self.gridLayout.addWidget(self.reader, 0, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.volume = QtWidgets.QLabel(Launch)
        self.volume.setObjectName("volume")
        self.horizontalLayout.addWidget(self.volume)
        self.volume_bar = QtWidgets.QSlider(Launch)
        self.volume_bar.setMaximum(100)
        self.volume_bar.setSingleStep(1)
        self.volume_bar.setPageStep(5)
        self.volume_bar.setProperty("value", 90)
        self.volume_bar.setOrientation(QtCore.Qt.Horizontal)
        self.volume_bar.setObjectName("volume_bar")
        self.horizontalLayout.addWidget(self.volume_bar)
        self.lvl_label = QtWidgets.QLabel(Launch)
        self.lvl_label.setObjectName("lvl_label")
        self.horizontalLayout.addWidget(self.lvl_label)
        self.lvl_combox = QtWidgets.QComboBox(Launch)
        self.lvl_combox.setObjectName("lvl_combox")
        self.lvl_combox.addItem("")
        self.lvl_combox.addItem("")
        self.lvl_combox.addItem("")
        self.lvl_combox.addItem("")
        self.lvl_combox.addItem("")
        self.lvl_combox.addItem("")
        self.lvl_combox.addItem("")
        self.lvl_combox.addItem("")
        self.lvl_combox.addItem("")
        self.lvl_combox.addItem("")
        self.lvl_combox.addItem("")
        self.lvl_combox.addItem("")
        self.lvl_combox.addItem("")
        self.lvl_combox.addItem("")
        self.horizontalLayout.addWidget(self.lvl_combox)
        self.pause_btn = QtWidgets.QPushButton(Launch)
        self.pause_btn.setObjectName("pause_btn")
        self.horizontalLayout.addWidget(self.pause_btn)
        self.gridLayout.addLayout(self.horizontalLayout, 2, 0, 1, 2)

        self.retranslateUi(Launch)
        self.pause_btn.clicked.connect(Launch.pause_read) # type: ignore
        self.lvl_combox.currentIndexChanged['int'].connect(Launch.temp_lvl_limit) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Launch)

    def retranslateUi(self, Launch):
        _translate = QtCore.QCoreApplication.translate
        Launch.setWindowTitle(_translate("Launch", "启动"))
        self.reciver.setText(_translate("Launch", "链接界面"))
        self.reader.setText(_translate("Launch", "读取界面"))
        self.volume.setText(_translate("Launch", "音量"))
        self.lvl_label.setText(_translate("Launch", "读取最低等级"))
        self.lvl_combox.setItemText(0, _translate("Launch", "0"))
        self.lvl_combox.setItemText(1, _translate("Launch", "1"))
        self.lvl_combox.setItemText(2, _translate("Launch", "2"))
        self.lvl_combox.setItemText(3, _translate("Launch", "3"))
        self.lvl_combox.setItemText(4, _translate("Launch", "4"))
        self.lvl_combox.setItemText(5, _translate("Launch", "5"))
        self.lvl_combox.setItemText(6, _translate("Launch", "6"))
        self.lvl_combox.setItemText(7, _translate("Launch", "7"))
        self.lvl_combox.setItemText(8, _translate("Launch", "8"))
        self.lvl_combox.setItemText(9, _translate("Launch", "9"))
        self.lvl_combox.setItemText(10, _translate("Launch", "10"))
        self.lvl_combox.setItemText(11, _translate("Launch", "15"))
        self.lvl_combox.setItemText(12, _translate("Launch", "20"))
        self.lvl_combox.setItemText(13, _translate("Launch", "21"))
        self.pause_btn.setText(_translate("Launch", "暂停"))
