# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'launchwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Launch(object):
    def setupUi(self, Launch):
        Launch.setObjectName("Launch")
        Launch.resize(593, 535)
        self.gridLayout = QtWidgets.QGridLayout(Launch)
        self.gridLayout.setObjectName("gridLayout")
        self.recivetext = QtWidgets.QTextBrowser(Launch)
        self.recivetext.setObjectName("recivetext")
        self.gridLayout.addWidget(self.recivetext, 1, 1, 1, 1)
        self.reciver = QtWidgets.QLabel(Launch)
        self.reciver.setObjectName("reciver")
        self.gridLayout.addWidget(self.reciver, 0, 1, 1, 1)
        self.readtext = QtWidgets.QTextBrowser(Launch)
        self.readtext.setObjectName("readtext")
        self.gridLayout.addWidget(self.readtext, 1, 0, 1, 1)
        self.reader = QtWidgets.QLabel(Launch)
        self.reader.setObjectName("reader")
        self.gridLayout.addWidget(self.reader, 0, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.volume = QtWidgets.QLabel(Launch)
        self.volume.setObjectName("volume")
        self.horizontalLayout.addWidget(self.volume)
        self.volume_bar = QtWidgets.QSlider(Launch)
        self.volume_bar.setMaximum(100)
        self.volume_bar.setSingleStep(1)
        self.volume_bar.setPageStep(5)
        self.volume_bar.setProperty("value", 90)
        self.volume_bar.setOrientation(QtCore.Qt.Horizontal)
        self.volume_bar.setObjectName("volume_bar")
        self.horizontalLayout.addWidget(self.volume_bar)
        self.gridLayout.addLayout(self.horizontalLayout, 2, 0, 1, 2)

        self.retranslateUi(Launch)
        self.volume_bar.sliderReleased.connect(Launch.volume_adjust) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Launch)

    def retranslateUi(self, Launch):
        _translate = QtCore.QCoreApplication.translate
        Launch.setWindowTitle(_translate("Launch", "启动"))
        self.reciver.setText(_translate("Launch", "链接界面"))
        self.reader.setText(_translate("Launch", "读取界面"))
        self.volume.setText(_translate("Launch", "音量"))
