# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'loginwindow.ui'
#
# Created by: PyQt5 ui code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LoginWindow(object):
    def setupUi(self, LoginWindow):
        LoginWindow.setObjectName("LoginWindow")
        LoginWindow.resize(260, 300)
        LoginWindow.setMinimumSize(QtCore.QSize(260, 300))
        LoginWindow.setMaximumSize(QtCore.QSize(260, 300))
        self.gridLayoutWidget = QtWidgets.QWidget(LoginWindow)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(50, 70, 171, 102))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.nplogin = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.nplogin.setContentsMargins(0, 0, 0, 0)
        self.nplogin.setObjectName("nplogin")
        self.pwl = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.pwl.setInputMask("")
        self.pwl.setText("")
        self.pwl.setEchoMode(QtWidgets.QLineEdit.Password)
        self.pwl.setObjectName("pwl")
        self.nplogin.addWidget(self.pwl, 1, 1, 1, 1)
        self.pw = QtWidgets.QLabel(self.gridLayoutWidget)
        self.pw.setObjectName("pw")
        self.nplogin.addWidget(self.pw, 1, 0, 1, 1)
        self.nnl = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.nnl.setEnabled(True)
        self.nnl.setInputMask("")
        self.nnl.setText("")
        self.nnl.setObjectName("nnl")
        self.nplogin.addWidget(self.nnl, 0, 1, 1, 1)
        self.nn = QtWidgets.QLabel(self.gridLayoutWidget)
        self.nn.setObjectName("nn")
        self.nplogin.addWidget(self.nn, 0, 0, 1, 1)
        self.nnl.raise_()
        self.pw.raise_()
        self.pwl.raise_()
        self.nn.raise_()
        self.pushButton = QtWidgets.QPushButton(LoginWindow)
        self.pushButton.setGeometry(QtCore.QRect(40, 200, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.comboBox = QtWidgets.QComboBox(LoginWindow)
        self.comboBox.setGeometry(QtCore.QRect(140, 30, 81, 22))
        self.comboBox.setFrame(True)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.checkBox = QtWidgets.QCheckBox(LoginWindow)
        self.checkBox.setGeometry(QtCore.QRect(140, 200, 71, 16))
        self.checkBox.setObjectName("checkBox")

        self.retranslateUi(LoginWindow)
        self.checkBox.clicked['bool'].connect(LoginWindow.loginwindow_save_password) # type: ignore
        self.comboBox.currentIndexChanged['int'].connect(LoginWindow.loginwindow_loginfunc_combox) # type: ignore
        self.pushButton.clicked.connect(LoginWindow.loginwindow_login) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(LoginWindow)

    def retranslateUi(self, LoginWindow):
        _translate = QtCore.QCoreApplication.translate
        LoginWindow.setWindowTitle(_translate("LoginWindow", "Form"))
        self.pwl.setPlaceholderText(_translate("LoginWindow", "password"))
        self.pw.setText(_translate("LoginWindow", "密码"))
        self.nnl.setPlaceholderText(_translate("LoginWindow", "nickname"))
        self.nn.setText(_translate("LoginWindow", "账号"))
        self.pushButton.setText(_translate("LoginWindow", "登录"))
        self.comboBox.setItemText(0, _translate("LoginWindow", "账号密码"))
        self.comboBox.setItemText(1, _translate("LoginWindow", "验证码"))
        self.comboBox.setItemText(2, _translate("LoginWindow", "二维码"))
        self.checkBox.setText(_translate("LoginWindow", "记住密码"))
