# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'settingswindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_settings_window(object):
    def setupUi(self, settings_window):
        settings_window.setObjectName("settings_window")
        settings_window.resize(334, 278)
        self.gridLayout_2 = QtWidgets.QGridLayout(settings_window)
        self.gridLayout_2.setObjectName("gridLayout_2")
        spacerItem = QtWidgets.QSpacerItem(40, 80, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 2, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem1, 1, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 40, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem2, 0, 1, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(80, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem3, 1, 2, 1, 1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.sessdate_line = QtWidgets.QLineEdit(settings_window)
        self.sessdate_line.setObjectName("sessdate_line")
        self.gridLayout.addWidget(self.sessdate_line, 0, 1, 1, 1)
        self.sessdate_label = QtWidgets.QLabel(settings_window)
        self.sessdate_label.setObjectName("sessdate_label")
        self.gridLayout.addWidget(self.sessdate_label, 0, 0, 1, 1)
        self.buvid3_label = QtWidgets.QLabel(settings_window)
        self.buvid3_label.setObjectName("buvid3_label")
        self.gridLayout.addWidget(self.buvid3_label, 2, 0, 1, 1)
        self.bili_jct_label = QtWidgets.QLabel(settings_window)
        self.bili_jct_label.setObjectName("bili_jct_label")
        self.gridLayout.addWidget(self.bili_jct_label, 1, 0, 1, 1)
        self.bili_jct_line = QtWidgets.QLineEdit(settings_window)
        self.bili_jct_line.setObjectName("bili_jct_line")
        self.gridLayout.addWidget(self.bili_jct_line, 1, 1, 1, 1)
        self.buvid3_line = QtWidgets.QLineEdit(settings_window)
        self.buvid3_line.setObjectName("buvid3_line")
        self.gridLayout.addWidget(self.buvid3_line, 2, 1, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 1, 1, 1, 1)
        self.ok = QtWidgets.QPushButton(settings_window)
        self.ok.setObjectName("ok")
        self.gridLayout_2.addWidget(self.ok, 3, 2, 1, 1)

        self.retranslateUi(settings_window)
        self.ok.clicked.connect(settings_window.save_and_close) # type: ignore
        self.buvid3_line.textChanged['QString'].connect(settings_window.text_changed) # type: ignore
        self.sessdate_line.textChanged['QString'].connect(settings_window.text_changed) # type: ignore
        self.bili_jct_line.textChanged['QString'].connect(settings_window.text_changed) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(settings_window)

    def retranslateUi(self, settings_window):
        _translate = QtCore.QCoreApplication.translate
        settings_window.setWindowTitle(_translate("settings_window", "设置"))
        self.sessdate_label.setText(_translate("settings_window", "SESSDATA"))
        self.buvid3_label.setText(_translate("settings_window", "buvid3"))
        self.bili_jct_label.setText(_translate("settings_window", "bili_jct"))
        self.ok.setText(_translate("settings_window", "保存并关闭"))
