# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'updatecontent.ui'
#
# Created by: PyQt5 ui code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_UpdateContent(object):
    def setupUi(self, UpdateContent):
        UpdateContent.setObjectName("UpdateContent")
        UpdateContent.resize(552, 426)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(UpdateContent.sizePolicy().hasHeightForWidth())
        UpdateContent.setSizePolicy(sizePolicy)
        self.gridLayout_2 = QtWidgets.QGridLayout(UpdateContent)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame = QtWidgets.QFrame(UpdateContent)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout.addWidget(self.frame)
        self.frame_2 = QtWidgets.QFrame(UpdateContent)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout.addWidget(self.frame_2)
        self.yep = QtWidgets.QPushButton(UpdateContent)
        self.yep.setObjectName("yep")
        self.horizontalLayout.addWidget(self.yep)
        self.gridLayout.addLayout(self.horizontalLayout, 2, 0, 1, 1)
        self.textBrowser = QtWidgets.QTextBrowser(UpdateContent)
        self.textBrowser.setObjectName("textBrowser")
        self.gridLayout.addWidget(self.textBrowser, 0, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)

        self.retranslateUi(UpdateContent)
        self.yep.clicked.connect(UpdateContent.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(UpdateContent)

    def retranslateUi(self, UpdateContent):
        _translate = QtCore.QCoreApplication.translate
        UpdateContent.setWindowTitle(_translate("UpdateContent", "Form"))
        self.yep.setText(_translate("UpdateContent", "好的"))
